### ISSUE TITLE
Sadad Gateway

### ISSUE THREAD

**Issue by Javid-Izadfar** [zegond/logos-per-banks#2]
First of all, thank you for making your work available for others. 
I've noticed you misspelled [Sadad ](https://sadadpsp.ir/)to _Sedad_.

**Comment by zegond** [comment]
Thanks for pointing this out.
I'll fix this in the next update :)

**Comment by sepidMo** [comment]
so clean.. great illustration.. love to see them in my symbol tab :) thanks a lot Pegah 👍

**Comment by zegond** [comment]
@Javid-Izadfar The typo has been resolved in V1.01. Please update. :)
